### PR TITLE
issue #31 changed sections to have max width $breakpoint-3

### PR DESCRIPTION
**Pull request by BryanSalas**

### CODE REVIEW

**Comment by MrBenJ** [comment]
Hey, thanks for opening a pull request!

Just one curiosity here: Is there a particular reason you chose 990px? Typically the breakpoint from an iPad (768px) to a desktop (1024px) display is 992px viewport to account for the padding on a full-width fluid or fixed container. This practice has been adopted in grid systems like bootstrap or foundation.

**Comment by BryanSalas** [comment]
I used the  breakpoint-3 as defined here:

`$space: 10px;`
`$susy: ( columns: 12, gutters: 0, math: fluid, output: float, last-flow: to, gutter-position: inside, global-box-sizing: border-box, );`
`$breakpoint-1: 320px - $space;`
`$breakpoint-2: 640px - $space;`
`$breakpoint-3: 1000px - $space;`
`$breakpoint-4: 1440px - $space;`
`$breakpoint-5: 1920px - $space;`

It ends up being 990px. I am for changing it, just wasn't sure if I should touch these globals.

**Comment by MrBenJ** [comment]
I'm actually not the one who defined those globals, but it would be super helpful to the git history if you could amend your commit message to say $breakpoint-3 instead of 990px. 

Just do a `git commit --amend` on your master branch, change the message, then force push up using `git push -f origin master`. Let me know once you've changed the message and I'll merge it in.

**Comment by BryanSalas** [comment]
Sure thing! Just updated the commit message.

**Pull request merged**
